export { default as Netflix } from './netflix.svg'
export { default as NetflixMini } from './netflix-mini.svg'
export { default as ArrowDown } from './arrow-down.svg'
export { default as Globe } from './globe.svg'
export { default as ArrowLeft } from './arrow-left.svg'