import type { NextPage } from 'next'
import Head from 'next/head'
import Header from 'components/header'
import Body from 'components/body'
import Footer from 'components/footer'
import Billboard from 'components/billboard'
import Collections from 'components/collections'
import More from 'components/more'
import getGenres, { Genres } from 'services/getGenres'

const Home: NextPage<{ genres: Genres[] }> = ({ genres }) => {
  return (
    <div css={{
      display: 'flex',
      flexFlow: 'column',
      minHeight: '100vh',
    }}>
      <Head>
        <title>Movies | Netflix Official Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Body login={false}>
        <Billboard title='Movies' synopsis="Movies move us like nothing else can, whether they’re scary, funny, dramatic, romantic or anywhere in-between. So many titles, so much to experience."/>
        {genres.map(({ id, name }) => (
          <Collections title={name} key={id} id={id} />
        ))}
      </Body>
      <More />
      <Footer />
    </div>
  )
}

Home.defaultProps = {
  genres: []
}

export async function getServerSideProps() {

  const genres = await getGenres()

  return {
    props: { genres: genres.slice(0, 5) },
  }
}

export default Home
